v1/Web-v1/Controllers/ArrangementsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Pixel.FixaBarnkalaset.Core;
using Pixel.FixaBarnkalaset.Core.Interfaces;
using Pixel.FixaBarnkalaset.Web.Models;

namespace Pixel.FixaBarnkalaset.Web.Controllers
{
    [Route("barnkalas")]
    public class ArrangementsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILogger<ArrangementsController> _logger;
        private readonly ICityRepository _cityRepository;
        private readonly IArrangementRepository _arrangementRepository;

        public ArrangementsController(IMapper mapper, ILogger<ArrangementsController> logger, ICityRepository cityRepository, IArrangementRepository arrangementRepository)
        {
            _mapper = mapper;
            _logger = logger;
            _cityRepository = cityRepository;
            _arrangementRepository = arrangementRepository;
        }

        [Route("{citySlug}")]
        public async Task<IActionResult> Index(string citySlug)
        {
            var city = await _cityRepository.GetBySlug(citySlug);
            if (city == null)
            {
                _logger.LogWarning("Index: No city with slug {Slug} found", citySlug);
                return NotFound();
            }

            ViewData["Title"] = $"Barnkalas i {city.Name} | Fixa barnkalaset";
            ViewData["Description"] = $"Här hittar du bra idéer för barnkalas i {city.Name}.";

            ViewData["OgTitle"] = $"Barnkalas i {city.Name}";
            ViewData["OgDescription"] = $"Här hittar du bra idéer för barnkalas i {city.Name}.";
            ViewData["OgImage"] = Request?.Scheme + "://" + Request?.Host + "/images/balloons-1869790_1200_630.jpg";

            var arrangements = city.Arrangements ?? new List<Arrangement>();
            return View(new ArrangementsIndexViewModel
            {
                CityName = city.Name,
                CitySlug = citySlug,
                Arrangements = _mapper.Map<IEnumerable<Arrangement>, IEnumerable<ArrangementsIndexViewModel.ArrangementViewModel>>(arrangements.OrderBy(a => a.Name))
            });
        }

        [Route("{citySlug}/{arrangementSlug}")]
        public async Task<IActionResult> Details(string citySlug, string arrangementSlug)
        {
            var city = await _cityRepository.GetBySlug(citySlug);
            if (city == null)
            {
                _logger.LogWarning("Details: No city with slug {CitySlug} found", citySlug);
                return NotFound();
            }

            var arrangement = await _arrangementRepository.GetBySlug(citySlug, arrangementSlug);
            if (arrangement == null)
            {
                _logger.LogWarning("Details: No arrangement with slug {ArrangementSlug} found", arrangementSlug);
                return NotFound();
            }

            ViewData["Title"] = $"Barnkalas på {arrangement.Name}, {city.Name} | Fixa barnkalaset";
            ViewData["Description"] = $"{arrangement.Pitch}";

            ViewData["OgTitle"] = $"Barnkalas på {arrangement.Name}, {city.Name}";
            ViewData["OgDescription"] = $"{arrangement.Pitch}";

            var viewModel = _mapper.Map<Arrangement, ArrangementDetailsViewModel>(arrangement);
            viewModel.CityName = city.Name;
            return View(viewModel);
        }
    }
}

v1/Web-v1/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Pixel.FixaBarnkalaset.Core;
using Pixel.FixaBarnkalaset.Core.Interfaces;
using Pixel.FixaBarnkalaset.Web.Models;
using Pixel.FixaBarnkalaset.Web.Utilities;

namespace Pixel.FixaBarnkalaset.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ICityRepository _cityRepository;
        private readonly IBlogPostRepository _blogPostRepository;
        private readonly ISitemapGenerator _sitemapGenerator;

        public HomeController(
            IMapper mapper,
            ICityRepository cityRepository,
            IBlogPostRepository blogPostRepository,
            ISitemapGenerator sitemapGenerator)
        {
            _mapper = mapper;
            _cityRepository = cityRepository;
            _blogPostRepository = blogPostRepository;
            _sitemapGenerator = sitemapGenerator;
        }

        [Route("")]
        public async Task<IActionResult> Index()
        {
            ViewData["Title"] = "Hitta det perfekta barnkalaset! | Fixa barnkalaset";
            ViewData["Description"] = "Vi har samlat en massa bra ställen som erbjuder nya spännande barnkalas för era barn och deras kompisar.";

            ViewData["OgTitle"] = "Hitta det perfekta barnkalaset!";
            ViewData["OgDescription"] = "Vi har samlat en massa bra ställen som erbjuder nya spännande barnkalas för era barn och deras kompisar.";
            ViewData["OgImage"] = Request?.Scheme + "://" + Request?.Host + "/images/balloons-1869790_1200_630.jpg";

            var cities = await _cityRepository.GetAll() ?? new List<City>();
            return View(new HomeIndexViewModel
            {
                Cities = _mapper.Map<IEnumerable<City>, IEnumerable<HomeIndexViewModel.CityViewModel>>(cities.OrderBy(c => c.Name))
            });
        }

        [Route("cookies")]
        public IActionResult Cookies()
        {
            ViewData["Title"] = "Cookies | Fixa barnkalaset";
            return View();
        }

        [Route("sitemap.xml")]
        public async Task<ActionResult> SitemapXml()
        {
            var xml = await _sitemapGenerator.GetAsString(_cityRepository, _blogPostRepository);
            return Content(xml, "application/xml");
        }
    }
}

v1/Web-v1/Controllers/InvitationCardsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pixel.FixaBarnkalaset.Web.Controllers
{
    [Route("inbjudningskort")]
    public class InvitationCardsController : Controller
    {
        [Route("")]
        public IActionResult Index()
        {
            ViewData["Title"] = "Inbjudningskort | Fixa barnkalaset";
            ViewData["Description"] = "Vi hjälper dig att designa, trycka och skicka inbjudningskorten.";
            return View();
        }
    }
}

v1/Web-v1/Controllers/RsvpController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pixel.FixaBarnkalaset.Web.Controllers
{
    [Route("osa")]
    public class RsvpController : Controller
    {
        [Route("")]
        public IActionResult Index()
        {
            ViewData["Title"] = "O.S.A. | Fixa barnkalaset";
            ViewData["Description"] = "Vi hjälper dig att hålla reda på vilka som kommer och inte kommer.";
            return View();
        }
    }
}

v1/Web-v1/Views/Home/Cookies.cshtml
<div class="ui main container pxl-public-page">
    <h1 class="ui header">Cookies</h1>
    <h2 class="ui medium header">Kakor på fixabarnkalaset.se</h2>

    <h3 class="ui header">Samtycke till kakor</h3>
    <p>Enligt lagen om elektronisk kommunikation ska alla som besöker en webbplats få information om webbplatsens användande av kakor (ofta kallat ”cookies”) och vad kakorna används till. Besökarens samtycke krävs om inte kakorna är nödvändiga för att tillhandahålla den tjänst som besökaren uttryckligen har begärt. Du ger ditt samtycke genom att själv acceptera användandet av kakor i din webbläsares säkerhetsinställningar.</p>

    <h3 class="ui header">Vad är en kaka?</h3>
    <p>En kaka är en textfil med information som används för att känna igen dig under kortare eller längre tid. Filen lagras på din dator och kan inte ställa till med någon skada. Det finns två olika typer av kakor, sessionskakor och fasta kakor. På fixabarnkalaset.se använder vi oss av båda typer av kakor.</p>

    <h3 class="ui header">Sessionskakor</h3>
    <p>På fixabarnkalaset.se använder vi sessionskakor för att vi ska kunna hålla isär olika användare eller för att kontrollera att du är inloggad. Sessionskakan innehåller användarens identitet och lagras tillfälligt i datorns minne under tiden du är uppkopplad mot fixabarnkalaset.se. När du loggar ut eller stänger ner din webbläsare försvinner den.</p>

    <h3 class="ui header">Fasta kakor</h3>
    <p>En fast kaka är en fil som sparas under längre tid och som gör att fixabarnkalaset.se kan känna igen dig vid ett återbesök. Nästa gång du besöker oss hittar fixabarnkalaset.se kakan och känner igen dig och de val du har gjort vid ett tidigare besök. Kakan kan även användas för att anpassa till exempel annonserbjudanden. En fast kaka stannar på din dator fram till det datum då kakan anses vara förbrukad, vilket kan variera beroende på vilket syfte kakan har.</p>

    <h3 class="ui header">Kakor för besöksstatistik</h3>
    <p>Vi jobbar hela tiden med att utveckla och göra webbplatsen bättre. För att vara framgångsrika i detta arbete analyserar vi den trafik som sker på fixabarnkalaset.se. Analysen sker med hjälp av ett statistikverktyg från en tredjepartsleverantör som använder sig av fasta kakor (så kallade ”tredjepartskakor”). Dessa kakor sparar ingen privat information om dig och är endast till för att göra vår besöksstatistik mer tillförlitlig.</p>

    <h3 class="ui header">Stänga av kakor</h3>
    <p>Om du inte samtycker till att kakor används kan du själv stänga av kakor i din webbläsares säkerhetsinställningar. Om du väljer att stänga av kakor kommer vissa delar av fixabarnkalaset.se inte att fungera korrekt.</p>

    <p>@Html.ActionLink("Tillbaka till förstasidan", "Index", "Home")</p>
</div>

v1/Web-v1/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Pixel.FixaBarnkalaset.Infrastructure.Identity
@using Pixel.FixaBarnkalaset.Web.Models
@model HomeIndexViewModel
@inject SignInManager<ApplicationUser> SignInManager

@section Hero 
{
    <div class="ui text container">
    <h1 class="ui inverted huge header">Hitta det perfekta barnkalaset</h1>
    <h3 class="ui inverted large header">Vi har samlat en massa bra ställen som erbjuder nya spännande barnkalas för era barn och deras kompisar.</h3>
    <select id="citySelector" class="dropdown pxl-first-page-hero-city-chooser">
        <option value="">Välj stad...</option>
        @foreach (var city in Model.Cities)
        {
            <option value="@Url.Action("Index", "Arrangements", new { citySlug = city.Slug })">@city.Name</option>
        }
    </select>
</div>
}

<div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
        <div class="center aligned row">
            <div class="column">
                <i class="huge mail outline icon"></i>
                <div class="pxl-text-container">
                    <h3 class="ui large header">Skicka riktiga inbjudningskort</h3>
                    <p>Vill du gärna skicka inbjudningskort med posten men inte riktigt känner att du har tid att köpa inbjudningskort, skriva adresser, klistra frimärken och lägga inbjudningskorten på posten så har vi den perfekta lösningen för dig.</p>
                </div>
                @Html.ActionLink("Läs mer", "Index", "InvitationCards", null, new { @class = "ui button" })
            </div>
            <div class="column">
                <i class="huge checked calendar icon"></i>
                <div class="pxl-text-container">
                    <h3 class="ui large header">Håll reda på vilka som kommer</h3>
                    <p>Känns det stökigt att hålla kolla på vilka som svarat och kanske lite pinsamt att påminna dem? Vi gör det superenkelt för dig att hålla reda på vilka som kommer till kalaset, inget mer bläddrande i inkorgen bland en massa meddelande eller e-post.</p>
                </div>
                @Html.ActionLink("Läs mer", "Index", "Rsvp", null, new { @class = "ui button"})
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $('select.dropdown').dropdown();
        $('select#citySelector').change(function() {
            if (window.ga) {
                var selectedCityName = $("option:selected", $(this)).text();
                ga('send',
                    'event',
                    {
                        eventCategory: 'Search',
                        eventAction: 'citySelector',
                        eventLabel: selectedCityName,
                        transport: 'beacon'
                    });
            }

            var selectedCityValue = $(this).val();
            if (selectedCityValue !== "") {
                window.location = selectedCityValue;
            }
        });
    </script>
}