Web/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Pixel.FixaBarnkalaset.Core;
using Pixel.FixaBarnkalaset.Core.Interfaces;
using Pixel.FixaBarnkalaset.Infrastructure.Identity;
using Pixel.FixaBarnkalaset.Web.Models;

namespace Pixel.FixaBarnkalaset.Web.Controllers
{
    [Route("barnkalasbloggen")]
    public class BlogPostsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILogger<BlogPostsController> _logger;
        private readonly IBlogPostRepository _blogPostRepository;

        public BlogPostsController(IMapper mapper, ILogger<BlogPostsController> logger, IBlogPostRepository blogPostRepository)
        {
            _mapper = mapper;
            _logger = logger;
            _blogPostRepository = blogPostRepository;
        }

        [Route("")]
        public async Task<IActionResult> Index()
        {
            var title = "Barnkalasbloggen";
            var description = "Vi på fixabarnkalaset.se samlar våra bästa tips och trix angående barnkalas i vår blogg.";

            ViewData["Title"] = $"{title} | Fixa barnkalaset";
            ViewData["Description"] = description;

            ViewData["OgTitle"] = title;
            ViewData["OgDescription"] = description;
            ViewData["OgImage"] = Request?.Scheme + "://" + Request?.Host + "/images/balloons-1869790_1200_630.jpg";

            var blogPosts = await _blogPostRepository.GetAll() ?? new BlogPost[0];
            return View(new BlogPostsIndexViewModel
            {
                BlogPosts = _mapper.Map<IEnumerable<BlogPost>, IEnumerable<BlogPostsIndexViewModel.BlogPostViewModel>>(
                    blogPosts
                        .Where(p => p.IsPublished && p.PublishedUtc < DateTime.UtcNow)
                        .OrderByDescending(p => p.PublishedUtc))
            });
        }

        [Route("{slug}")]
        public async Task<IActionResult> Details(string slug)
        {
            var blogPost = await _blogPostRepository.GetBySlug(slug);
            if (blogPost == null)
            {
                _logger.LogWarning("Details: No blog post with slug {Slug} found", slug);
                return NotFound();
            }

            if ((User == null || !User.IsInRole(Roles.Admin)) && !blogPost.IsPublished || blogPost.PublishedUtc > DateTime.UtcNow)
            {
                _logger.LogWarning("Details: Blog post with slug {Slug} is not published yet", slug);
                return NotFound();
            }

            ViewData["Title"] = $"{blogPost.Title} | Fixa barnkalaset";
            ViewData["Description"] = LimitLength(blogPost.Body, 160, true);

            ViewData["OgTitle"] = blogPost.Title;
            ViewData["OgDescription"] = LimitLength(blogPost.Body, 300, true);
            ViewData["OgImage"] = Request?.Scheme + "://" + Request?.Host + "/images/balloons-1869790_1200_630.jpg";

            var viewModel = _mapper.Map<BlogPost, BlogPostDetailsViewModel>(blogPost);
            return View(viewModel);
        }


        private static string LimitLength(string inputString, int length, bool appendEllipsis)
        {
            var strippedInput = StripHtml(inputString);
            if (appendEllipsis)
            {
                return strippedInput.Length <= length ? strippedInput : $"{strippedInput.Substring(0, length - 3)}...";
            }
            else
            {
                return strippedInput.Length <= length ? strippedInput : strippedInput.Substring(0, length);
            }
        }

        private static string StripHtml(string inputString)
        {
            if (inputString == null) return "";
            return Regex.Replace(inputString, "<.*?>", "");
        }
    }
}

Web/Views/BlogPosts/Details.cshtml
@model Pixel.FixaBarnkalaset.Web.Models.BlogPostDetailsViewModel

<div class="container pxl-public-page pxl-blog-posts-details-page">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home" )">Hem</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "BlogPosts" )">Barnkalasbloggen</a></li>
        </ol>
    </nav>

    <article itemscope itemtype="http://schema.org/BlogPosting" class="mb-4 mb-md-5">

        <h1 class="text-center mb-3" itemprop="name">@Model.Title</h1>

        @if (Model.PublishedUtc.HasValue)
        {
            <p class="text-center" itemprop="datePublished">@Model.PublishedUtc.Value.ToLocalTime().ToString("dd MMMM yyyy")</p>
        }

        <div itemprop="articleBody">@Html.Raw(Model.Body)</div>
    </article>
</div>

Web/Views/BlogPosts/Index.cshtml
@model Pixel.FixaBarnkalaset.Web.Models.BlogPostsIndexViewModel

<div class="container pxl-public-page pxl-blog-posts-index-page">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Hem</a></li>
            <li class="breadcrumb-item active" aria-current="page">Barnkalasbloggen</li>
        </ol>
    </nav>

    <h1 class="text-center mb-4 mb-md-5">Barnkalasbloggen</h1>

    <div class="items" itemscope itemtype="http://schema.org/Blog">
        @foreach (var blogPost in Model.BlogPosts)
        {
            <article class="item mb-5" itemprop="blogPosts" itemscope itemtype="http://schema.org/BlogPosting">
                <div class="content">
                    <h2 class="text-center">
                        @Html.ActionLink(blogPost.Title, "Details", new { slug = blogPost.Slug }, new { @class = "", itemprop = "name" })
                    </h2>
                    @if (blogPost.PublishedUtc.HasValue)
                    {
                        <p class="text-center" itemprop="datePublished">@blogPost.PublishedUtc.Value.ToLocalTime().ToString("dd MMMM yyyy")</p>
                    }
                    <div class="description" itemprop="articleBody">
                        @Html.Raw(blogPost.Body)
                    </div>
                </div>
            </article>
        }
    </div>
</div>